# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ZeroLiam can code
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Some of my coding y'all
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://zeroliam.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  ZeroLiam
github_url: "https://github.com/ZeroLiam"

#GitHub vars
site.github.owner_name: ZeroLiam
site.github.owner_url: "https://github.com/ZeroLiam"

# Build settings
name: ZeroLiam can code
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

permalink: /blog/:year/:month/:day/:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
